export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT = 'LOGOUT';

export const GET_CURRENTUSER_REQUEST = 'GET_CURRENTUSER_REQUEST';
export const GET_CURRENTUSER_FAILURE = 'GET_CURRENTUSER_FAILURE';
export const GET_CURRENTUSER_SUCCESS = 'GET_CURRENTUSER_SUCCESS';

export const GET_ALLARTICLES_REQUEST = 'GET_ALLARTICLES_REQUEST';
export const GET_ALLARTICLES_FAILURE = 'GET_ALLARTICLES_FAILURE';
export const GET_ALLARTICLES_SUCCESS = 'GET_ALLARTICLES_SUCCESS';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const GET_ALLPROFILES_REQUEST = 'GET_ALLPROFILES_REQUEST';
export const GET_ALLPROFILES_FAILURE = 'GET_ALLPROFILES_FAILURE';
export const GET_ALLPROFILES_SUCCESS = 'GET_ALLPROFILES_SUCCESS';

export const GET_ALLALBUMS_REQUEST = 'GET_ALLALBUMS_REQUEST';
export const GET_ALLALBUMS_FAILURE = 'GET_ALLALBUMS_FAILURE';
export const GET_ALLALBUMS_SUCCESS = 'GET_ALLALBUMS_SUCCESS';

export const GET_BANNERS_REQUEST = 'GET_BANNERS_REQUEST';
export const GET_BANNERS_FAILURE = 'GET_BANNERS_FAILURE';
export const GET_BANNERS_SUCCESS = 'GET_BANNERS_SUCCESS';

export const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST';
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';

export const GET_ALLDOWNLOADLINKS_REQUEST = 'GET_ALLDOWNLOADLINKS_REQUEST';
export const GET_ALLDOWNLOADLINKS_FAILURE = 'GET_ALLDOWNLOADLINKS_FAILURE';
export const GET_ALLDOWNLOADLINKS_SUCCESS = 'GET_ALLDOWNLOADLINKS_SUCCESS';

export const GET_MYARTICLES_REQUEST = 'GET_MYARTICLES_REQUEST';
export const GET_MYARTICLES_FAILURE = 'GET_MYARTICLES_FAILURE';
export const GET_MYARTICLES_SUCCESS = 'GET_MYARTICLES_SUCCESS';

export const CREATE_ARTICLE_REQUEST = 'CREATE_ARTICLE_REQUEST';
export const CREATE_ARTICLE_FAILURE = 'CREATE_ARTICLE_FAILURE';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';

export const CREATE_ALBUM_REQUEST = 'CREATE_ALBUM_REQUEST';
export const CREATE_ALBUM_FAILURE = 'CREATE_ALBUM_FAILURE';
export const CREATE_ALBUM_SUCCESS = 'CREATE_ALBUM_SUCCESS';

export const CREATE_BANNER_REQUEST = 'CREATE_BANNER_REQUEST';
export const CREATE_BANNER_FAILURE = 'CREATE_BANNER_FAILURE';
export const CREATE_BANNER_SUCCESS = 'CREATE_BANNER_SUCCESS';

export const DELETE_BANNER_REQUEST = 'DELETE_BANNER_REQUEST';
export const DELETE_BANNER_FAILURE = 'DELETE_BANNER_FAILURE';
export const DELETE_BANNER_SUCCESS = 'DELETE_BANNER_SUCCESS';

export const GET_USERINFO_REQUEST = 'GET_USERINFO_REQUEST';
export const GET_USERINFO_FAILURE = 'GET_USERINFO_FAILURE';
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS';

export const GET_PUBLISHEDARTICLES_REQUEST = 'GET_PUBLISHEDARTICLES_REQUEST';
export const GET_PUBLISHEDARTICLES_FAILURE = 'GET_PUBLISHEDARTICLES_FAILURE';
export const GET_PUBLISHEDARTICLES_SUCCESS = 'GET_PUBLISHEDARTICLES_SUCCESS';

export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';

export const GET_MYALBUM_REQUEST = 'GET_MYALBUM_REQUEST';
export const GET_MYALBUM_FAILURE = 'GET_MYALBUM_FAILURE';
export const GET_MYALBUM_SUCCESS = 'GET_MYALBUM_SUCCESS';

export const GET_ARTICLEINFO_REQUEST = 'GET_ARTICLEINFO_REQUEST';
export const GET_ARTICLEINFO_FAILURE = 'GET_ARTICLEINFO_FAILURE';
export const GET_ARTICLEINFO_SUCCESS = 'GET_ARTICLEINFO_SUCCESS';

export const UPDATE_FEATUREDALBUM_REQUEST = 'UPDATE_FEATUREDALBUM_REQUEST';
export const UPDATE_FEATUREDALBUM_FAILURE = 'UPDATE_FEATUREDALBUM_FAILURE';
export const UPDATE_FEATUREDALBUM_SUCCESS = 'UPDATE_FEATUREDALBUM_SUCCESS';

export const UPDATE_ALBUMPICTURE_REQUEST = 'UPDATE_ALBUMPICTURE_REQUEST';
export const UPDATE_ALBUMPICTURE_FAILURE = 'UPDATE_ALBUMPICTURE_FAILURE';
export const UPDATE_ALBUMPICTURE_SUCCESS = 'UPDATE_ALBUMPICTURE_SUCCESS';

export const UPDATE_ALBUMVIDEO_REQUEST = 'UPDATE_ALBUMVIDEO_REQUEST';
export const UPDATE_ALBUMVIDEO_FAILURE = 'UPDATE_ALBUMVIDEO_FAILURE';
export const UPDATE_ALBUMVIDEO_SUCCESS = 'UPDATE_ALBUMVIDEO_SUCCESS';

export const INVITE_USERS_REQUEST = 'INVITE_USERS_REQUEST';
export const INVITE_USERS_FAILURE = 'INVITE_USERS_FAILURE';
export const INVITE_USERS_SUCCESS = 'INVITE_USERS_SUCCESS';

export const GET_PUBLISHEDALBUMS_REQUEST = 'GET_PUBLISHEDALBUMS_REQUEST';
export const GET_PUBLISHEDALBUMS_FAILURE = 'GET_PUBLISHEDALBUMS_FAILURE';
export const GET_PUBLISHEDALBUMS_SUCCESS = 'GET_PUBLISHEDALBUMS_SUCCESS';

export const UPDATE_ACCOUNTSTATUS_REQUEST = 'UPDATE_ACCOUNTSTATUS_REQUEST';
export const UPDATE_ACCOUNTSTATUS_FAILURE = 'UPDATE_ACCOUNTSTATUS_FAILURE';
export const UPDATE_ACCOUNTSTATUS_SUCCESS = 'UPDATE_ACCOUNTSTATUS_SUCCESS';

export const EDIT_USERINFO_REQUEST = 'EDIT_USERINFO_REQUEST';
export const EDIT_USERINFO_FAILURE = 'EDIT_USERINFO_FAILURE';
export const EDIT_USERINFO_SUCCESS = 'EDIT_USERINFO_SUCCESS';

export const UPDATE_ARTICLESTATUS_REQUEST = 'UPDATE_ARTICLESTATUS_REQUEST';
export const UPDATE_ARTICLESTATUS_FAILURE = 'UPDATE_ARTICLESTATUS_FAILURE';
export const UPDATE_ARTICLESTATUS_SUCCESS = 'UPDATE_ARTICLESTATUS_SUCCESS';

export const PUBLISH_ARTICLE_REQUEST = 'PUBLISH_ARTICLE_REQUEST';
export const PUBLISH_ARTICLE_FAILURE = 'PUBLISH_ARTICLE_FAILURE';
export const PUBLISH_ARTICLE_SUCCESS = 'PUBLISH_ARTICLE_SUCCESS';

export const ADD_PROFILE_REQUEST = 'ADD_PROFILE_REQUEST';
export const ADD_PROFILE_FAILURE = 'ADD_PROFILE_FAILURE';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';

export const GET_PROFILEINFO_REQUEST = 'GET_PROFILEINFO_REQUEST';
export const GET_PROFILEINFO_FAILURE = 'GET_PROFILEINFO_FAILURE';
export const GET_PROFILEINFO_SUCCESS = 'GET_PROFILEINFO_SUCCESS';

export const DELETE_PROFILE_REQUEST = 'DELETE_PROFILE_REQUEST';
export const DELETE_PROFILE_FAILURE = 'DELETE_PROFILE_FAILURE';
export const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS';

export const ADD_TAG_REQUEST = 'ADD_TAG_REQUEST';
export const ADD_TAG_FAILURE = 'ADD_TAG_FAILURE';
export const ADD_TAG_SUCCESS = 'ADD_TAG_SUCCESS';

export const DELETE_TAG_REQUEST = 'DELETE_TAG_REQUEST';
export const DELETE_TAG_FAILURE = 'DELETE_TAG_FAILURE';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';

export const UPDATE_ALBUMSTATUS_REQUEST = 'UPDATE_ALBUMSTATUS_REQUEST';
export const UPDATE_ALBUMSTATUS_FAILURE = 'UPDATE_ALBUMSTATUS_FAILURE';
export const UPDATE_ALBUMSTATUS_SUCCESS = 'UPDATE_ALBUMSTATUS_SUCCESS';

export const ADD_DOWNLOAD_REQUEST = 'ADD_DOWNLOAD_REQUEST';
export const ADD_DOWNLOAD_FAILURE = 'ADD_DOWNLOAD_FAILURE';
export const ADD_DOWNLOAD_SUCCESS = 'ADD_DOWNLOAD_SUCCESS';

export const EDIT_DOWNLOAD_REQUEST = 'EDIT_DOWNLOAD_REQUEST';
export const EDIT_DOWNLOAD_FAILURE = 'EDIT_DOWNLOAD_FAILURE';
export const EDIT_DOWNLOAD_SUCCESS = 'EDIT_DOWNLOAD_SUCCESS';

export const PUBLISH_ALBUM_REQUEST = 'PUBLISH_ALBUM_REQUEST';
export const PUBLISH_ALBUM_FAILURE = 'PUBLISH_ALBUM_FAILURE';
export const PUBLISH_ALBUM_SUCCESS = 'PUBLISH_ALBUM_SUCCESS';

export const DELETE_DOWNLOAD_REQUEST = 'DELETE_DOWNLOAD_REQUEST';
export const DELETE_DOWNLOAD_FAILURE = 'DELETE_DOWNLOAD_FAILURE';
export const DELETE_DOWNLOAD_SUCCESS = 'DELETE_DOWNLOAD_SUCCESS';

export const UPDATE_ALBUMINFO_REQUEST = 'UPDATE_ALBUMINFO_REQUEST';
export const UPDATE_ALBUMINFO_FAILURE = 'UPDATE_ALBUMINFO_FAILURE';
export const UPDATE_ALBUMINFO_SUCCESS = 'UPDATE_ALBUMINFO_SUCCESS';

export const GET_ALBUMINFO_REQUEST = 'GET_ALBUMINFO_REQUEST';
export const GET_ALBUMINFO_FAILURE = 'GET_ALBUMINFO_FAILURE';
export const GET_ALBUMINFO_SUCCESS = 'GET_ALBUMINFO_SUCCESS';

export const UPDATE_ARTICLEINFO_REQUEST = 'UPDATE_ARTICLEINFO_REQUEST';
export const UPDATE_ARTICLEINFO_FAILURE = 'UPDATE_ARTICLEINFO_FAILURE';
export const UPDATE_ARTICLEINFO_SUCCESS = 'UPDATE_ARTICLEINFO_SUCCESS';

export const GET_PENDINGARTICLES_REQUEST = 'GET_PENDINGARTICLES_REQUEST';
export const GET_PENDINGARTICLES_FAILURE = 'GET_PENDINGARTICLES_FAILURE';
export const GET_PENDINGARTICLES_SUCCESS = 'GET_PENDINGARTICLES_SUCCESS';

export const GET_APPROVEDARTICLES_REQUEST = 'GET_APPROVEDARTICLES_REQUEST';
export const GET_APPROVEDARTICLES_FAILURE = 'GET_APPROVEDARTICLES_FAILURE';
export const GET_APPROVEDARTICLES_SUCCESS = 'GET_APPROVEDARTICLES_SUCCESS';

export const GET_REJECTEDARTICLES_REQUEST = 'GET_REJECTEDARTICLES_REQUEST';
export const GET_REJECTEDARTICLES_FAILURE = 'GET_REJECTEDARTICLES_FAILURE';
export const GET_REJECTEDARTICLES_SUCCESS = 'GET_REJECTEDARTICLES_SUCCESS';

export const GET_APPROVEDALBUMS_REQUEST = 'GET_APPROVEDALBUMS_REQUEST';
export const GET_APPROVEDALBUMS_FAILURE = 'GET_APPROVEDALBUMS_FAILURE';
export const GET_APPROVEDALBUMS_SUCCESS = 'GET_APPROVEDALBUMS_SUCCESS';

export const GET_PENDINGALBUMS_REQUEST = 'GET_PENDINGALBUMS_REQUEST';
export const GET_PENDINGALBUMS_FAILURE = 'GET_PENDINGALBUMS_FAILURE';
export const GET_PENDINGALBUMS_SUCCESS = 'GET_PENDINGALBUMS_SUCCESS';

export const GET_REJECTEDALBUMS_REQUEST = 'GET_REJECTEDALBUMS_REQUEST';
export const GET_REJECTEDALBUMS_FAILURE = 'GET_REJECTEDALBUMS_FAILURE';
export const GET_REJECTEDALBUMS_SUCCESS = 'GET_REJECTEDALBUMS_SUCCESS';

export const GET_PUBLICPHOTOS_REQUEST = 'GET_PUBLICPHOTOS_REQUEST';
export const GET_PUBLICPHOTOS_FAILURE = 'GET_PUBLICPHOTOS_FAILURE';
export const GET_PUBLICPHOTOS_SUCCESS = 'GET_PUBLICPHOTOS_SUCCESS';

export const GET_PRIVATEPHOTOS_REQUEST = 'GET_PRIVATEPHOTOS_REQUEST';
export const GET_PRIVATEPHOTOS_FAILURE = 'GET_PRIVATEPHOTOS_FAILURE';
export const GET_PRIVATEPHOTOS_SUCCESS = 'GET_PRIVATEPHOTOS_SUCCESS';

export const ADD_PHOTOS_REQUEST = 'ADD_PHOTOS_REQUEST';
export const ADD_PHOTOS_FAILURE = 'ADD_PHOTOS_FAILURE';
export const ADD_PHOTOS_SUCCESS = 'ADD_PHOTOS_SUCCESS';

export const UPDATE_FEATUREDARTICLE_REQUEST = 'UPDATE_FEATUREDARTICLE_REQUEST';
export const UPDATE_FEATUREDARTICLE_FAILURE = 'UPDATE_FEATUREDARTICLE_FAILURE';
export const UPDATE_FEATUREDARTICLE_SUCCESS = 'UPDATE_FEATUREDARTICLE_SUCCESS';

export const DELETE_ALBUM_REQUEST = 'DELETE_ALBUM_REQUEST';
export const DELETE_ALBUM_FAILURE = 'DELETE_ALBUM_FAILURE';
export const DELETE_ALBUM_SUCCESS = 'DELETE_ALBUM_SUCCESS';

export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST';
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
